/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ProductController;
import Controller.SalesController;
import Model.Product;
import Model.Sales;
import com.toedter.calendar.JDateChooser;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KESTROY
 */
public class SalesInterface extends javax.swing.JFrame {
      private SalesController controller;

    /**
     * Creates new form NewJFrame
     */
    public SalesInterface() {
        initComponents();
        controller = new SalesController(this);
        loadSalesData();
    }
    
     private void loadSalesData() {
        try {
            List<Sales> sales = controller.getAllSales();
            DefaultTableModel model = (DefaultTableModel) salesTable.getModel();
            model.setRowCount(0);
            for (Sales sale : sales) {
                model.addRow(new Object[]{
                    sale.getId(),
                    sale.getProductId(),
                    sale.getCustomerName(),
                    sale.getQuantity(),
                    sale.getTotalPrice(),
                    sale.getsaleDate()
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading sales data!");
        }
    }

    private void clearFields() {
        productidTF.setText("");
        customernameTF.setText("");
        quantityTF.setText("");
        totalpriceTF.setText("");
        saledateTF = new JDateChooser();
        saledateTF.setDate(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        productidTF = new javax.swing.JTextField();
        customernameTF = new javax.swing.JTextField();
        totalpriceTF = new javax.swing.JTextField();
        quantityTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        salesTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        saledateTF = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        addBTN = new javax.swing.JButton();
        View = new javax.swing.JButton();
        updateBTN = new javax.swing.JButton();
        DeleteBTN = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Close = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(193, 50));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Product ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 116, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Customer Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 158, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Total Price");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 242, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Quantity");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        productidTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(productidTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 117, 160, -1));

        customernameTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customernameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customernameTFActionPerformed(evt);
            }
        });
        getContentPane().add(customernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 159, 160, -1));

        totalpriceTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(totalpriceTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 243, 160, -1));

        quantityTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(quantityTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 201, 160, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Sale Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 284, -1, -1));

        salesTable.setAutoCreateRowSorter(true);
        salesTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        salesTable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        salesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sales ID", "Product ID", "Customer Name", "Quantity", "Total Price", "Sale Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        salesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(salesTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 910, 180));

        jLabel7.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel7.setText("Sales Details");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 970, 10));
        getContentPane().add(saledateTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 284, 160, -1));

        jPanel1.setBackground(new java.awt.Color(255, 153, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        addBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addBTN.setForeground(new java.awt.Color(0, 0, 102));
        addBTN.setText("Add");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        View.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        View.setForeground(new java.awt.Color(0, 0, 102));
        View.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-view-30.png"))); // NOI18N
        View.setText("View");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });

        updateBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateBTN.setForeground(new java.awt.Color(0, 0, 102));
        updateBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-update-30.png"))); // NOI18N
        updateBTN.setText("Update");
        updateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBTNActionPerformed(evt);
            }
        });

        DeleteBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DeleteBTN.setForeground(new java.awt.Color(0, 0, 102));
        DeleteBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-delete-30.png"))); // NOI18N
        DeleteBTN.setText("Delete");
        DeleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBTNActionPerformed(evt);
            }
        });

        Clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Clear.setForeground(new java.awt.Color(0, 0, 102));
        Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-clear-30.png"))); // NOI18N
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        Close.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Close.setForeground(new java.awt.Color(0, 0, 102));
        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-exit-30.png"))); // NOI18N
        Close.setText("Exit");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });

        add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(0, 0, 102));
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-add-30.png"))); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1090, 1090, 1090)
                        .addComponent(addBTN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateBTN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DeleteBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(Clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(View, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(addBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(updateBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteBTN)
                    .addComponent(View))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clear)
                    .addComponent(Close))
                .addGap(157, 157, 157))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 320, 160));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/backg.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesTableMouseClicked
        // TODO add your handling code here:
       int selectedRow = salesTable.getSelectedRow();
        productidTF.setText(salesTable.getValueAt(selectedRow, 1).toString());
        customernameTF.setText(salesTable.getValueAt(selectedRow, 2).toString());
        quantityTF.setText(salesTable.getValueAt(selectedRow, 3).toString());
        totalpriceTF.setText(salesTable.getValueAt(selectedRow, 4).toString());
         try {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        String dateString = salesTable.getValueAt(selectedRow, 4).toString();
        java.util.Date date = dateFormat.parse(dateString);
        saledateTF.setDate(date);
    } catch (Exception e) {
        e.printStackTrace();
        saledateTF.setDate(null); // set to null if date conversion fails
    }
    }//GEN-LAST:event_salesTableMouseClicked

    private void customernameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customernameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customernameTFActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_addBTNActionPerformed

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        // TODO add your handling code here:
         try {
            int selectedRow = salesTable.getSelectedRow();
            if (selectedRow != -1) {
                String details = "Sale Details:\n";
                details += "Product ID: " + salesTable.getValueAt(selectedRow, 1).toString() + "\n";
                details += "Customer Name: " + salesTable.getValueAt(selectedRow, 2).toString() + "\n";
                details += "Quantity: " + salesTable.getValueAt(selectedRow, 3).toString() + "\n";
                details += "Total Price: " + salesTable.getValueAt(selectedRow, 4).toString() + "\n";
                details += "Sale Date: " + salesTable.getValueAt(selectedRow, 5).toString();
                JOptionPane.showMessageDialog(this, details, "Sale Details", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Please select a sale to view!");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error viewing sale!");
        }
    }//GEN-LAST:event_ViewActionPerformed

    private void updateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBTNActionPerformed
        // TODO add your handling code here:
       int selectedRow = salesTable.getSelectedRow();
        if (selectedRow != -1) {
            Sales sale = new Sales();
            sale.setId((int) salesTable.getValueAt(selectedRow, 0));
            sale.setProductId(Integer.parseInt(productidTF.getText()));
            sale.setCustomerName(customernameTF.getText());
            sale.setQuantity(Integer.parseInt(quantityTF.getText()));
            sale.setTotalPrice(Double.parseDouble(totalpriceTF.getText()));
           
            SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
            String purchaseDate = dFormat.format(saledateTF.getDate());
            sale.setsaleDate(purchaseDate);

            try {
                controller.updateSale(sale);
                loadSalesData();
                clearFields();
                JOptionPane.showMessageDialog(this, "Sale updated successfully!");
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error updating product!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a product to update!");
        }
    }//GEN-LAST:event_updateBTNActionPerformed

    private void DeleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBTNActionPerformed
        // TODO add your handling code here:
       int selectedRow = salesTable.getSelectedRow();
        if (selectedRow != -1) {
            int saleId = (int) salesTable.getValueAt(selectedRow, 0);
            try {
                controller.deleteSale(saleId);
                loadSalesData();
                clearFields();
                JOptionPane.showMessageDialog(this, "Sale deleted successfully!");
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error deleting sale!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a sale to delete!");
        }
    }//GEN-LAST:event_DeleteBTNActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_ClearActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_CloseActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        Sales sale = new Sales();
        sale.setProductId(Integer.parseInt(productidTF.getText()));
        sale.setCustomerName(customernameTF.getText());
        sale.setQuantity(Integer.parseInt(quantityTF.getText()));
        sale.setTotalPrice(Double.parseDouble(totalpriceTF.getText()));
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        String saleDate = dFormat.format(saledateTF.getDate());
        sale.setsaleDate(saleDate);

        try {
            controller.addSale(sale);
            loadSalesData();
            clearFields();
            JOptionPane.showMessageDialog(this, "Sale added successfully!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error adding sale!");
        }
    }//GEN-LAST:event_addActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // Ensure GUI is created on the Event Dispatch Thread
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Close;
    private javax.swing.JButton DeleteBTN;
    private javax.swing.JButton View;
    private javax.swing.JButton add;
    private javax.swing.JButton addBTN;
    private javax.swing.JTextField customernameTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField productidTF;
    private javax.swing.JTextField quantityTF;
    private com.toedter.calendar.JDateChooser saledateTF;
    private javax.swing.JTable salesTable;
    private javax.swing.JTextField totalpriceTF;
    private javax.swing.JButton updateBTN;
    // End of variables declaration//GEN-END:variables

    
}
